Proyecto_Final_IA_Dermatologia/urls.py
"""
Configuración de URLs de Django
Este archivo contiene los patrones de URL para el proyecto Django.
Incluye rutas para la aplicación principal, la aplicación de dermatología, la aplicación central y la interfaz de administración.
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                path('admin/', admin.site.urls),
                path('', include('apps.auth.urls')),
                path('core/', include('apps.core.urls')),
                path('dermatology/', include('apps.Dermatologia_IA.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Dermatologia_IA/urls.py
from django.urls import path

from .views.generateReport_and_sendReportEmail import GenerateReportView, SendReportEmailView
from .views.view_report_user_IA import *

app_name = 'dermatology'

urlpatterns = [
  path('upload/', UploadImageView.as_view(), name='upload_image'),
  path('search-patients/', SearchPatientsView.as_view(), name='search_patients'),
  path('process/<int:image_id>/', ProcessImageView.as_view(), name='process_image'),  # result
  path('reports/list/', ReportListView.as_view(), name='report_list'),
  path('report_details/<int:image_id>/', ReportDetailView.as_view(), name='report_detail'),

  path('generate/report/<int:image_id>/', GenerateReportView.as_view(), name='generate_report'),
  path('send_report_email/<int:image_id>/', SendReportEmailView.as_view(), name='send_report_email'),

  path('pacientes/', PatientListView.as_view(), name='patient-list'),
  path('pacientes/nuevo/', PatientCreateView.as_view(), name='patient-create'),
  path('pacientes/<int:pk>/editar/', PatientUpdateView.as_view(), name='patient-update'),
]

apps/auth/urls.py
"""
Configuración de URLs para la aplicación auth.
Incluye rutas para registro, inicio de sesión, cierre de sesión,
restablecimiento de contraseña y gestión del perfil de usuario.
"""

from django.contrib.auth import views as auth_views
from django.urls import path

from apps.auth.views.view_auth import (
  RegisterUserView,
  LoginUserView,
  LogoutUserView,
  PasswordResetRequestView,
  CustomPasswordResetConfirmView
)
from apps.auth.views.view_profile import ProfileView, UpdateProfileView

app_name = 'auth'

urlpatterns = [
  path('register/', RegisterUserView.as_view(), name='register'),
  path('', LoginUserView.as_view(), name='login'),
  path('logout/', LogoutUserView.as_view(), name='logout'),

  path('profile/', ProfileView.as_view(), name='view_profile'),
  path('profile/update/', UpdateProfileView.as_view(), name='update_profile'),

  path('password-reset/',
       PasswordResetRequestView.as_view(),
       name='password_reset'),

  path('password-reset-confirm/<uidb64>/<token>/',
       CustomPasswordResetConfirmView.as_view(),
       name='password_reset_confirm'),

  path('password-reset-complete/',
       auth_views.PasswordResetCompleteView.as_view(
         template_name='auth/reset_password/password_reset_complete.html'
       ),
       name='password_reset_complete'),
]

apps/core/urls.py
"""
Configuración de URLs para el módulo core.
Incluye rutas para la página principal y características del sistema.
"""

from django.urls import path

from apps.core.views.views import (
  HomeView,
  CharacteristicsView
)

app_name = 'core'

urlpatterns = [
  path('home/', HomeView.as_view(), name='home'),
  path('characteristics/', CharacteristicsView.as_view(), name='characteristics'),
]

templates/components/base.html
<!DOCTYPE html>
<html lang="es">
<head>
  {% load static %}
  <!-- Meta tags básicos -->
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'img/icon_dermIA.png' %}" type="image/x-icon">

  <!-- Título dinámico de la página -->
  <title>
    {% block title %} {{ page_title }} - {{ app_name }} {% endblock %}
  </title>

  <!-- Estilos base -->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
  <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
  />
  <!-- Font Awesome -->
  <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  />

  <!-- Estilos adicionales específicos de cada página -->
  {% block extra_css %}{% endblock %}
</head>
<body>
<div class="app-container">
  <!-- Barra lateral de navegación -->
  {% include 'components/sidebar.html' %}

  <!-- Contenido principal -->
  <main class="main-content">
    <!-- Sistema de mensajes/alertas -->
    {% include "includes/messages.html" %}

    <!-- Contenido específico de cada página -->
    {% block content %}{% endblock %}
  </main>
</div>

<!-- Scripts adicionales específicos de cada página -->
<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

{% block extra_js %}{% endblock %}
</body>
</html>

templates/components/sidebar.html
{% load static %}

<div class="sidebar">
    <!-- Encabezado del sidebar con logo -->
    <div class="sidebar-header">
        <div class="logo">
            <div class="logo-icon">
                <img src="{% static 'img/icon.png' %}"
                     alt="{{ app_name }} Logo"
                     class="logo-image"/>
            </div>
            <span class="logo-text">{{ app_name }}</span>
        </div>
    </div>

    <!-- Menú de navegación principal -->
    <nav class="sidebar-nav">
        <ul class="nav-list">
            <!-- Item Home -->
            <li class="nav-item {% if current_page == 'home' %}active{% endif %}">
                <a href="{% url 'core:home' %}" class="nav-link">
                    <i class="fas fa-home"></i>
                    <span>Inicio</span>
                </a>
            </li>

            <!-- Item Características -->
            <li class="nav-item {% if current_page == 'characteristics' %}active{% endif %}">
                <a href="{% url 'core:characteristics' %}" class="nav-link">
                   <i class="fas fa-puzzle-piece"></i>
                    <span>Características</span>
                </a>
            </li>

            <!-- Item Análisis -->
            <li class="nav-item {% if current_page == 'analysis' %}active{% endif %}">
                <a href="{% url 'dermatology:upload_image' %}" class="nav-link">
                    <i class="fas fa-chart-line"></i>
                    <span>Análisis de imágenes</span>
                </a>
            </li>

            <!-- Item Reportes -->
            <li class="nav-item {% if current_page == 'reports' %}active{% endif %}">
                <a href="{% url 'dermatology:report_list' %}" class="nav-link">
                    <i class="fas fa-file-alt"></i>
                    <span>Reportes</span>
                </a>
            </li>

            <!-- Item Pacientes -->
            <li class="nav-item {% if current_page == 'patients' %}active{% endif %}">
                <a href="{% url 'dermatology:patient-list' %}" class="nav-link">
                    <i class="fas fa-users"></i>
                    <span>Pacientes</span>
                </a>
            </li>
        </ul>
    </nav>

    <!-- Pie del sidebar -->
    <div class="sidebar-footer">
        <!-- Enlaces de perfil y cierre de sesión -->
        <div class="nav-item {% if current_page == 'profile' %}active{% endif %}">
            <a href="{% url 'auth:view_profile' %}" class="nav-link">
                <i class="fas fa-user"></i>
                <span>Perfil</span>
            </a>
        </div>
        <div class="nav-item">
            <a href="{% url 'auth:logout' %}" class="nav-link">
                <i class="fas fa-sign-out-alt"></i>
                <span>Cerrar sesión</span>
            </a>
        </div>

        <!-- Información del usuario -->
        <div class="user-info">
            <!-- Avatar del usuario -->
            <div class="user-avatar">
                {% if user.profile_picture %}
                    <img class="profile-picture"
                         src="{{ user.profile_picture.url }}"
                         alt="Foto de perfil"/>
                {% else %}
                    <img class="profile-picture"
                         src="{% static 'img/avatar.jpg' %}"
                         alt="Foto de perfil predeterminada"/>
                {% endif %}
            </div>

            <!-- Detalles del usuario -->
            <div class="user-details">
                {% if user.is_authenticated %}
                    <span class="user-name">
                        Dr. {{ user.get_full_name|default:"Usuario" }}
                    </span>
                    <span class="user-email">{{ user.email }}</span>
                {% endif %}
            </div>
        </div>
    </div>
</div>